# Generated by Django 5.2.7 on 2025-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_packetdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('thread', 'Threads')], default='facebook', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'platform', '-generated_at'], name='accounts_re_user_id_e62a5f_idx'),
        ),
    ]
