# Generated by Django 5.2.7 on 2025-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='platform',
            field=models.CharField(db_index=True, default='unknown', max_length=30),
        ),
    ]
