# Generated by Django 5.2.7 on 2025-12-16 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_report_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, max_length=30)),
                ('is_spam', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'platform', 'created_at'], name='accounts_pa_user_id_f62dac_idx')],
            },
        ),
    ]
